### PR TITLE
add oauth & cookie authorization, AuthService

### PR DESCRIPTION
**Pull request by alexgivi**
I didn't check working. If you don't set access token param in config, basic authorization is used.

### CODE REVIEW

**Comment by alexgivi** [comment]
also implement cookie session authorization.
Add AuthService.
Add getInstance() static method to JiraClient, and now it is possible to use also static singletones of services, i.e. `IssueService::getInstance()->someMethod();` it's need to pass configuration when call `getInstance(new ArrayConfiguration([....]))` first time, because of creation static object.
Static instance of AuthService used to store, get session cookie info, and to login and logout. It used internally if cookie authorization enabled.

**Comment by lesstif** [comment]
hi @alexgivi .

i think that session cookie also need to set the option CURLOPT_COOKIEFILE and CURLOPT_COOKIEJAR.

i will squash your commit to single commit and add small code.

thanks.

**Comment by larowlan** [comment]
Are there any docs on using this? The main docs still reference using passwords which is not encouraged.
Would be willing to update docs if could get some guidance on using it.

**Comment by larowlan** [comment]
Thanks

**Pull request closed without merging**
