### PR TITLE
WIP remove $configuration, and clean up exec, upload and download

### PR DESCRIPTION
**Pull request by Richard87**
WIP

Solves #355

### CODE REVIEW

**Comment by Richard87** [comment]
What? this is not ready :S

**Comment by lesstif** [comment]
hi @Richard87 

i'm sorry, i was not meticulous at this PR, so this PR is build broken.

could make hot fix please?

**Comment by Richard87** [comment]
Hi! I'm not sure if I can?

I think you'll have to revert the commit, and push a new head, but I'm not good enough in Git, or have access to the git repository to make it happen...

I can delete all my changes, and make a new commit with basically 0 changes, so you can merge it in?

**Comment by lesstif** [comment]
hi!

i'm remove your PR and revert master branch to last commit.

if you are create new PR branch,  you should send to 3.0.0-alpha branch please.

thanks!.

**Comment by Richard87** [comment]
Great, thats perfect!

**Pull request merged**
