### PR TITLE
Feature: Add personal certificate support to connect to jira

### PR DESCRIPTION
**Pull request by timomayer**
I extended your awesome library to support client certificates to access a jira instance.
would love to see this merged :)

### CODE REVIEW

**Comment by timomayer** [comment]
will update the pr with the nitpick-ci feedback

**Comment by lesstif** [comment]
hi @timomayer  

i will be merge from styleci PR, so you don't need to update PR.

thanks.

**Comment by lesstif** [comment]
@timomayer 
i'm using PHPstan for static code analyzer, but PHPstan complains with below result.

could you update PR  with fixing PHPStan's complain please?

* https://travis-ci.org/github/lesstif/php-jira-rest-client/jobs/691131465

```sh
 ------ ----------------------------------------------------------------------- 

  Line   Configuration/AbstractConfiguration.php                                

 ------ ----------------------------------------------------------------------- 

  205    Access to an undefined property                                        

         JiraRestApi\Configuration\AbstractConfiguration::$curlOptSslCert.      

  213    Access to an undefined property                                        

         JiraRestApi\Configuration\AbstractConfiguration::$curlOptSslCertPassw  

         ord.                                                                   

  221    Access to an undefined property                                        

         JiraRestApi\Configuration\AbstractConfiguration::$curlOptSslKey.       

  229    Access to an undefined property                                        

         JiraRestApi\Configuration\AbstractConfiguration::$curlOptSslKeyPasswo  

         rd.                                                                    

 ------ ----------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 

  Line   Configuration/ArrayConfiguration.php                                   

 ------ ----------------------------------------------------------------------- 

  26     Access to an undefined property                                        

         JiraRestApi\Configuration\ArrayConfiguration::$curlOptSslCert.         

  27     Access to an undefined property                                        

         JiraRestApi\Configuration\ArrayConfiguration::$curlOptSslCertPassword  

         .                                                                      

  28     Access to an undefined property                                        

         JiraRestApi\Configuration\ArrayConfiguration::$curlOptSslKey.          

  29     Access to an undefined property                                        

         JiraRestApi\Configuration\ArrayConfiguration::$curlOptSslKeyPassword.  

 ------ ----------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 

  Line   Configuration/DotEnvConfiguration.php                                  

 ------ ----------------------------------------------------------------------- 

  32     Access to an undefined property                                        

         JiraRestApi\Configuration\DotEnvConfiguration::$curlOptSslCert.        

  33     Access to an undefined property                                        

         JiraRestApi\Configuration\DotEnvConfiguration::$curlOptSslCertPasswor  

         d.                                                                     

  34     Access to an undefined property                                        

         JiraRestApi\Configuration\DotEnvConfiguration::$curlOptSslKey.         

  35     Access to an undefined property                                        

         JiraRestApi\Configuration\DotEnvConfiguration::$curlOptSslKeyPassword  

         .                                                                      

 ------ ----------------------------------------------------------------------- 
```

**Comment by timomayer** [comment]
Awesome thanks, can you please release a new version with this fix? then i can switch back from my forked version to your repo for composer reference :)

**Comment by lesstif** [comment]
hi @timomayer 

i wanna release stable repository only.
you can access the master branch through just fork this repository. :)

thanks!

**Pull request merged**
