### PR TITLE
Improvement of IssueService::getComments method

### PR DESCRIPTION
**Pull request by rmuradyan**
Fixed error in IssueService::getComments method.

### CODE REVIEW

**Comment by rmuradyan** [comment]
Big thank you for your library!

**Comment by lesstif** [comment]
@rmuradyan thanks for your contribution.

before merge to your changes, i was run get comments feature on my JIRA Instance(standalone 8.2.3), but working correctly.

could you to explain why this PR is hotfix?

**Comment by rmuradyan** [comment]
Hi! Changed the title.
Should I target this PR to develop branch?

**Comment by lesstif** [comment]
hi @rmuradyan 

i could't get the any exception with _getComments()_ method.

could you explain to me that your environment and more information(error message, stack trace, etc...)  for fixing problem please?

**Comment by rmuradyan** [comment]
Yes. Exception is not got. But target structure is not right. We create a Comment object when expected to get Comments object, that was designed for it. That's an error.

**Comment by rmuradyan** [comment]
The point is target structure of getComments method supposed to be Comments object, but Comment object is given. We should pass a "Comments" object to the mapper to map fields correctly. So that json fields were mapped to the object of Comments class that has all the necessary fields, such as "total", "comments", "startAt" and "maxResults" and is intended for this. Now all the fields are filling into a Comment object, that is incorrect.

**Comment by lesstif** [comment]
hi @rmuradyan 

your PR does't based on the latest sources.

could you pull latest and resend PR please.? (see #306 )

**Pull request closed without merging**
