### PR TITLE
Allow read and write of properties

### PR DESCRIPTION
**Pull request by Schrank**

### CODE REVIEW

**Comment by lesstif** [comment]
Hi @Schrank, Happy new year & Thank you for your contributions.

Could you revise your PR 2 things, please?

1. to drop the PHPDoc base annotation & to modify to strict type hint like below.

**before**
```php
/** @var string */
public $key;
```

**after**
```php
public string $key;
```

2. add example code and documentation link into README.doc

**Comment by Schrank** [comment]
@lesstif Happy new year! - Am I correct, that you need to wait another three weeks, before you celebrate? Or do you celebrate the "European" new year as well? Or am I totally wrong? I remember to read something about Korean New Year is not the same day as "ours" 😅 

Please have a look on the changes, wether they are as you want them :-)

And thanks for this awesome lib, saved SOO much time - and was easy to extend <3

**Comment by lesstif** [comment]
@Schrank Korean are celebrating the European new year and the lunar new year both. :)
Repeat again, Thank you for your volunteering.

**Comment by Schrank** [comment]
> Korean are celebrating the European new year and the lunar new year both. :)
Repeat again

Lucky you!

Thanks for merging <3

**Pull request merged**
