### PR TITLE
change type of project lead from array to string

### LINKED ISSUE #421: $project->setLead() expects array even thought it should be array
According to https://github.com/lesstif/php-jira-rest-client#create-project creating a project works via

```
    $p = new Project();

    $p->setKey('EX')
        ....
        ->setLead('lesstif')
        ....;
```

which results in PHPStorm showing the following warning:

image

because inside the project class your phpdoc expect the given parameter to be an array, not a string.
https://github.com/lesstif/php-jira-rest-client/blob/main/src/Project/Project.php#L206

I couldn't find an example where `setLead()` uses an array nor did I find a test using it like it is defined in the phpdoc.

I will create a PR which changes that to `string` so static analysis tools like phpstan or pslam don't complain.

### PR DESCRIPTION
**Pull request by LordSimal**
Closes #421

### CODE REVIEW

**Comment by RikvdHeijden** [comment]
This change seems to have broken the ProjectService's get function. I get the error `JSON property "lead" in class "JiraRestApi\Project\Project" is an object and cannot be converted to a string` when the project gets populated because lead is an object (not an array) in de API response (https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-issuetypescheme-project-put). 

There is a disconnect between the datatype Jira expects when creating or updating a project and the datatype Jira returns when querying the project. I haven't taken the time to dig further into the module to see if there are any other places this has been done and handeled.

Changing the parameters type to mixed seems to be a quick fix, though I suppose the correct way to handle this is to use different data objects for querying and submitting Projects. Would that be possible in the module as it stands @lesstif?

**Comment by lesstif** [comment]
Hi @LordSimal @RikvdHeijden 

Sorry, It's my mistake, Honestly, I forget to this library doesn't match PHPDoc.

I'm reverted to the old version, @RikvdHeijden do you have a chance to confirm this modification work correctly, please?

**Comment by LordSimal** [comment]
Since this is only the phpdoc type can't we just allow both old and new?
So like `@var array|string` and `@param array|string $lead`?
This would also fix my problem since my static code anylsis tool doesn't scream at me.

**Comment by RikvdHeijden** [comment]
@LordSimal 
In my experimenting it seems that isn't an option because the system that hydrates these models with the API response data uses the param type hint to do some typechecking on the data (hence the exception I encountered) this system does not seem to be able to handle the array|string case.

@lesstif 
reverting the change fixes my issue but I do agree with @LordSimal that this is not very intuitive. While it might not be the ideal solution I think making the type mixed and adding some additional documentation to the docblock might be the best bang-for-the-buck fix. Since every other solution I can come up with is at the very least a breaking change for some workflow or another.

Regardless ot the solution you choose to implement I'd like to thank both of you for the quick replies and handling of this issue.

**Comment by lesstif** [comment]
@LordSimal @RikvdHeijden Thank you for your feedback.

Honestly, I'm on the same page about this library not very intuitive.

But there are several reasons.
when I started this project I didn't understand correctly how the external JSON mapper library worked.

At that time I have written code like Java's getter/setter like below.

When JSON mapper works as serializer/deserialize,  it scan the PHPDoc and resolves the target type.
However, IssueType parameters can be strings or IssueType classes.
As a result JSON mapper call the _setIssueType_ function with $IssueType Param, But IssueType param will be either string or IssueType class.

if you're modified PHPDoc 

```php
 /**
     * set issue type.
     *
     * @param IssueType $issueType mixed IssueType or string
     *
     * @return $this
     */
    public function setIssueType($issueType)
{
}
```

**Pull request merged**
