### PR TITLE
#91 start pulling velocity by sprint

### PR DESCRIPTION
**Pull request by donkidd**
This update adds the ability to pull Board & Sprint Info from Jira as well as Committed and Completed Points for a particular sprint.  
This update also added BoardService and SprintService and made them unit testable.

### CODE REVIEW

**Comment by donkidd** [comment]
After the CI Failed, I realized that I made a bigger change then I realized in regards to PHPUnit.  I updated the phpunit requirement to be 
>         "phpunit/phpunit": "^7.0.0",
This is mainly because the phpunit that was listed, support ended on February 2, 2018.  And the 6.0 version ends support on Feb. 1, 2019 so I thought it might make sense to just jump to the 7.0 version.  This then brakes your CI tests and you are no longer php 5 or 6 compatible as phpunit 7 requires 
PHP 7.1, PHP 7.2, PHP 7.3

**Comment by lesstif** [comment]
hi @donkidd 

thanks for your contributions.

i have a some request for your PR.

1. please to downgrade phpunit 7 to 5 in the composer.json, because all CI test case was broken.
1. please squash all commits.
1. README.md file looks like have many changes, but most change is CR/LF. fix it please

thanks.

**Comment by donkidd** [comment]
@lesstif 
I have Squashed and I think I updated the current tests you have so they should work with the new version of PHPUnit.  between 5 & 7 they changed what the name of the class was that you extend for a testCase which is why the tests failed.  

As for the Readme file yes there were some spaces, but I did add a lot of documentation at the end of the readme file to explain how the Board & Sprint classes could be called using how you had documented them as an example.  Please let me know if the tests work for you.

**Comment by lesstif** [comment]
hi @donkidd 

this library have supporting PHP 5.6, but PHPUnit 7  support PHP 7 only.

sorry but i could't merge your PR unless you downgrade to PHPUnit 5.

thanks.

**Comment by donkidd** [comment]
But isn't 5.6 end of life this year?  Shouldn't we all start moving away
from 5.6 and toward 7?

**Comment by donkidd** [comment]
What about making a php7 branch and using it to release your 2.0.0 version
of the code?

**Comment by lesstif** [comment]
it's a good suggestion, but i can't it being start now.

**Comment by donkidd** [comment]
So, should I start my branch over and use it to make a 2.0 aka PHP 7
version?

**Pull request closed without merging**
